### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by AndrewBrinker** [finchers-rs/finchers#1]
This project looks awesome, and I am happy to help write documentation! My usual strategy is to add `#![deny(missing_docs)]` to the crate, and then go through and add documentation one bit at a time, removing the macro periodically to commit. Any thoughts you have about how you want documentation done for this?

We can also measure against the Rust API Guidelines, which are super useful: https://rust-lang-nursery.github.io/api-guidelines/documentation.html

**Comment by ubnt-intrepid** [comment]
Thanks for reporting the issue!

I'll soon add `#![deny(missing_docs)]` to the crates's root, and finishing to write documentation until v0.2.0.

**Comment by AndrewBrinker** [comment]
Sounds good! I'm happy to help as well, if there are places you'd like attention focused. Having fresh eyes may help with making sure documentation is clear to new users.

**Comment by ubnt-intrepid** [comment]
moved to https://github.com/finchers-rs/guide/issues/1
