### ISSUE TITLE
More consistent path matchers

### ISSUE THREAD

**Issue by 6D65** [finchers-rs/finchers#11]
Hi,

First things first, congratulations on a great project.

I was wondering what's your opinion on replacing the string_ magic thing with a generic method.

Changing this to this:

```rust
    let endpoint = get("hello".with(string_))
        .join(param::<String>("foo"))
        .map(|(name, param)| Json(format!("Hello, {}, {}", name, param)));
```

to this

```rust
    let endpoint = get("hello".with<String>("name"))
        .join(param::<String>("foo"))
        .map(|(name, param)| Json(format!("Hello, {}, {}", name, param)));
```

or even rename it to slash as it feels more fluent

```rust
    let endpoint = get("hello".slash<String>("name"))
        .join(param::<String>("foo"))
        .map(|(name, param)| Json(format!("Hello, {}, {}", name, param)));
```

or remove the "name" string from the call as it's not used

```rust
    let endpoint = get("hello".slash<String>())
        .join(param::<String>("foo"))
        .map(|(name, param)| Json(format!("Hello, {}, {}", name, param)));
```

**Comment by ubnt-intrepid** [comment]
@6D65 First, thanks for your valuable proposal!

In my opinion, the role of combinators (`With`, `Join`, etc.) should be kept on the general purpose, not path matching... So I'll keep the specification of current combinators.

But also, the consistence of path matching is also important.
Fortunately, you can add a method to the `Endpoint` by defining the trait externally.
For example, the fourth proposal (`.slash::<T>()`) can be implemented as follows:

```rust
trait EndpointExt: Sized {
    fn slash<T: FromStr>(self) -> With<Self, Path<T>>;
}

impl<E:Endpoint + Sized> EndpointExt for E {
    fn slash<T: FromStr>(self) -> With<Self, Path<T>> {
        self.with(path::<T>())
    }
}
```

```rust
let endpoint = get( "hello".slash<String>() )  // is matched "GET /hello/<String>"
```

**Comment by ubnt-intrepid** [comment]
I'm also considering the definition of path matcher, by using (procedural) macros.
It assumes that it will look as follows:

```rust
let endpoint = route!(GET "/hello/<name:String>", foo:String)
    .map(|(name, foo)| { ... })
```

**Comment by 6D65** [comment]
Cool,

I agree that simplicity it's better. But will keep in mind of the ability to extend the endpoint.
I'm not sure if it's possible since your type it's defined in a different crate.

Anyway, it already looks great. This is not a big one.
