### ISSUE TITLE
HTTP module

### ISSUE THREAD

**Issue by djKooks** [finchers-rs/finchers#229]
It looks like current project is based on hyper module.
Is there any specific reason? Just question...

**Comment by ubnt-intrepid** [comment]
The main reason for using Hyper is that it is the most widely used and actively developed among the Rust's HTTP libraries supporting the asynchronous I/O at the moment.

If other HTTP libraries, like tower-web (described in [this post](https://medium.com/@carllerche/announcing-tower-a-library-for-writing-robust-network-services-with-rust-67273f052c40)) will be released and their community will be likely to mature enough, it will have possiblity to add the support for getting on its ecosystem.

**Comment by djKooks** [comment]
@ubnt-intrepid Seems good. Thanks.
